version: '3.8'
services:
  php74mssql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74mssql
    ports:
      - "8080:80"
    networks:
      - php74mssql-network

networks:
  php74mssql-network:
