version: '3.8'

services:
  mssql2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrongPassword123
      MSSQL_PID: Express
      MSSQL_ENCRYPT: 0
    ports:
      - "1439:1433"
    volumes:
      - sqlserver2019data:/var/opt/mssql
    networks:
      - hoursmanager-network

  hoursmanager:
    build:
      context: .
      dockerfile: Dockerfile
    # image: kooldev/php:7.4-nginx-sqlsrv
    container_name: hoursmanager
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=80
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - mssql2019
    networks:
      - hoursmanager-network

volumes:
  sqlserver2019data:

networks:
  hoursmanager-network:

# Testing MSSQL COnnection : /opt/mssql-tools18/bin/sqlcmd -S "localhost,1439" -U sa -P "YourStrongPassword123"
# Testing MSSQL COnnection : /opt/mssql-tools18/bin/sqlcmd -S "sqlserver2019" -U sa -P "YourStrongPassword123"
# Testing MSSQL COnnection : /opt/mssql-tools18/bin/sqlcmd -S "DESKTOP-NT6E2QE\SQLEXPRESS"

